#!/bin/bash

#############################################
# Quick Setup Guide
# Step-by-step instructions for complete setup
#############################################

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     AWS Static Website with CloudFront & SSL Certificate      ║"
echo "║                    Complete Setup Guide                        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Domain: bmiostad.ostaddevops.click"
echo "Bucket: ostad-devops-batch-10 (ap-south-1)"
echo "Profile: sarowar-ostad"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "PHASE 1: SSL CERTIFICATE (Run on Ubuntu 24.04)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "These steps must be run on Ubuntu 24.04 with root/sudo access"
echo ""
echo "Step 1: Install Certbot"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 01-install-certbot.sh"
echo ""
echo "  What it does:"
echo "  • Installs Certbot and Route53 DNS plugin"
echo "  • Verifies installation"
echo ""
echo ""
echo "Step 2: Request SSL Certificate"
echo "────────────────────────────────────────────────────────────────"
echo "  ⚠️  FIRST: Edit 02-request-certificate.sh and update EMAIL!"
echo ""
echo "  bash 02-request-certificate.sh"
echo ""
echo "  What it does:"
echo "  • Requests Let's Encrypt certificate via DNS-01 challenge"
echo "  • Automatically creates DNS TXT records in Route53"
echo "  • Verifies domain ownership"
echo "  • Issues certificate (valid for 90 days)"
echo ""
echo ""
echo "Step 3: Export Certificate Files"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 03-export-certificate.sh"
echo ""
echo "  What it does:"
echo "  • Exports certificate files from /etc/letsencrypt/"
echo "  • Saves to ./ssl-certs/ directory"
echo "  • Prepares files for ACM import"
echo ""
echo ""
echo "Step 4: Import to AWS ACM"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 04-import-to-acm.sh"
echo ""
echo "  What it does:"
echo "  • Imports certificate to AWS ACM in us-east-1"
echo "  • Required region for CloudFront"
echo "  • Saves certificate ARN to certificate-arn.txt"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "PHASE 2: AWS INFRASTRUCTURE (Run anywhere with AWS CLI)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "These steps can be run on any machine with AWS CLI configured"
echo ""
echo "Step 5: Create S3 Bucket"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 05-create-s3-bucket.sh"
echo ""
echo "  What it does:"
echo "  • Creates private S3 bucket in ap-south-1"
echo "  • Uploads index.html and error.html"
echo "  • Enables static website hosting"
echo "  • Keeps bucket private (Block Public Access enabled)"
echo ""
echo ""
echo "Step 6a: Create CloudFront OAC"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 06-create-cloudfront-oac.sh"
echo ""
echo "  What it does:"
echo "  • Creates Origin Access Control for CloudFront"
echo "  • Enables secure access to private S3 bucket"
echo "  • Saves OAC ID to oac-id.txt"
echo ""
echo ""
echo "Step 6b: Create CloudFront Distribution"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 06-create-cloudfront.sh"
echo ""
echo "  What it does:"
echo "  • Creates CloudFront distribution"
echo "  • Configures S3 origin with OAC"
echo "  • Attaches SSL certificate"
echo "  • Sets up custom domain"
echo "  • Enables HTTPS redirect"
echo "  • Configures custom error responses"
echo "  • Saves distribution ID and domain"
echo ""
echo "  ⏳ Takes 5-15 minutes to deploy globally"
echo ""
echo ""
echo "Step 7: Update S3 Bucket Policy"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 07-update-bucket-policy.sh"
echo ""
echo "  What it does:"
echo "  • Updates bucket policy to allow CloudFront OAC access"
echo "  • Restricts access to specific CloudFront distribution"
echo "  • Keeps bucket private to public"
echo ""
echo ""
echo "Step 8: Create Route53 DNS Record"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 08-create-route53-record.sh"
echo ""
echo "  What it does:"
echo "  • Creates A record (IPv4) in Route53"
echo "  • Creates AAAA record (IPv6) in Route53"
echo "  • Points domain to CloudFront distribution"
echo "  • Uses Alias records (no query charges)"
echo ""
echo "  ⏳ DNS propagation: 5-60 minutes"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "VERIFICATION"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "After DNS propagation completes, test your website:"
echo ""
echo "Test HTTPS access:"
echo "  curl -I https://bmiostad.ostaddevops.click"
echo ""
echo "Test HTTP redirect:"
echo "  curl -I http://bmiostad.ostaddevops.click"
echo ""
echo "Test SSL certificate:"
echo "  openssl s_client -connect bmiostad.ostaddevops.click:443"
echo ""
echo "Test DNS resolution:"
echo "  nslookup bmiostad.ostaddevops.click"
echo "  dig bmiostad.ostaddevops.click"
echo ""
echo "Open in browser:"
echo "  https://bmiostad.ostaddevops.click"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "CERTIFICATE RENEWAL (Every 60-80 days)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Let's Encrypt certificates expire every 90 days"
echo ""
echo "Step 9: Renew Certificate"
echo "────────────────────────────────────────────────────────────────"
echo "  bash 09-renew-certificate.sh"
echo ""
echo "  What it does:"
echo "  • Renews certificate with Certbot"
echo "  • Exports renewed certificate"
echo "  • Re-imports to ACM (same ARN)"
echo "  • CloudFront automatically uses renewed certificate"
echo ""
echo "📅 Set a calendar reminder to run this every 60 days!"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "STATUS CHECKER"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Check setup progress at any time:"
echo "  bash 00-check-status.sh"
echo ""
echo "This shows:"
echo "  • Which steps are completed"
echo "  • What needs to be done next"
echo "  • Certificate expiry status"
echo "  • Useful commands"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "CloudFront deployment status:"
echo "  aws cloudfront get-distribution \\"
echo "    --id \$(cat distribution-id.txt) \\"
echo "    --profile sarowar-ostad \\"
echo "    --query 'Distribution.Status'"
echo ""
echo "Check Route53 record:"
echo "  aws route53 list-resource-record-sets \\"
echo "    --hosted-zone-id Z1019653XLWIJ02C53P5 \\"
echo "    --profile sarowar-ostad \\"
echo "    --query 'ResourceRecordSets[?Name==\`bmiostad.ostaddevops.click.\`]'"
echo ""
echo "Check certificate in ACM:"
echo "  aws acm describe-certificate \\"
echo "    --certificate-arn \$(cat certificate-arn.txt) \\"
echo "    --region us-east-1 \\"
echo "    --profile sarowar-ostad"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "IMPORTANT NOTES"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✓ Certificate must be in us-east-1 for CloudFront"
echo "✓ S3 bucket can be in any region (we use ap-south-1)"
echo "✓ Bucket is private - only accessible via CloudFront"
echo "✓ Let's Encrypt certificates expire every 90 days"
echo "✓ DNS propagation can take 5-60 minutes"
echo "✓ CloudFront deployment takes 5-15 minutes"
echo "✓ Never commit ssl-certs/ directory to git"
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "NEED HELP?"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Read the complete documentation:"
echo "  cat README.md"
echo ""
echo "Or open README.md in your preferred text editor/browser"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
